IF NOT EXISTS ( SELECT 1 FROM AvailableDates WHERE available_date='2020-05-25' AND campsite_id=1) BEGIN INSERT INTO AvailableDates( available_date, campsite_id, isAvailable ) VALUES ( '2020-05-25', 1, 1 ) END
IF NOT EXISTS ( SELECT 1 FROM AvailableDates WHERE available_date='2020-05-26' AND campsite_id=1) BEGIN INSERT INTO AvailableDates( available_date, campsite_id, isAvailable ) VALUES ( '2020-05-26', 1, 1 ) END
IF NOT EXISTS ( SELECT 1 FROM AvailableDates WHERE available_date='2020-05-27' AND campsite_id=1) BEGIN INSERT INTO AvailableDates( available_date, campsite_id, isAvailable ) VALUES ( '2020-05-27', 1, 1 ) END
IF NOT EXISTS ( SELECT 1 FROM AvailableDates WHERE available_date='2020-05-28' AND campsite_id=1) BEGIN INSERT INTO AvailableDates( available_date, campsite_id, isAvailable ) VALUES ( '2020-05-28', 1, 1 ) END
IF NOT EXISTS ( SELECT 1 FROM AvailableDates WHERE available_date='2020-05-29' AND campsite_id=1) BEGIN INSERT INTO AvailableDates( available_date, campsite_id, isAvailable ) VALUES ( '2020-05-29', 1, 1 ) END
IF NOT EXISTS ( SELECT 1 FROM AvailableDates WHERE available_date='2020-05-30' AND campsite_id=1) BEGIN INSERT INTO AvailableDates( available_date, campsite_id, isAvailable ) VALUES ( '2020-05-30', 1, 1 ) END
IF NOT EXISTS ( SELECT 1 FROM AvailableDates WHERE available_date='2020-05-31' AND campsite_id=1) BEGIN INSERT INTO AvailableDates( available_date, campsite_id, isAvailable ) VALUES ( '2020-05-31', 1, 1 ) END
IF NOT EXISTS ( SELECT 1 FROM AvailableDates WHERE available_date='2020-06-01' AND campsite_id=1) BEGIN INSERT INTO AvailableDates( available_date, campsite_id, isAvailable ) VALUES ( '2020-06-01', 1, 1 ) END
IF NOT EXISTS ( SELECT 1 FROM AvailableDates WHERE available_date='2020-06-02' AND campsite_id=1) BEGIN INSERT INTO AvailableDates( available_date, campsite_id, isAvailable ) VALUES ( '2020-06-02', 1, 1 ) END
IF NOT EXISTS ( SELECT 1 FROM AvailableDates WHERE available_date='2020-06-03' AND campsite_id=1) BEGIN INSERT INTO AvailableDates( available_date, campsite_id, isAvailable ) VALUES ( '2020-06-03', 1, 1 ) END
																																							   						   
IF NOT EXISTS ( SELECT 1 FROM AvailableDates WHERE available_date='2020-05-25' AND campsite_id=2) BEGIN INSERT INTO AvailableDates( available_date, campsite_id, isAvailable ) VALUES ( '2020-05-25', 2, 1 ) END
IF NOT EXISTS ( SELECT 1 FROM AvailableDates WHERE available_date='2020-05-26' AND campsite_id=2) BEGIN INSERT INTO AvailableDates( available_date, campsite_id, isAvailable ) VALUES ( '2020-05-26', 2, 1 ) END
IF NOT EXISTS ( SELECT 1 FROM AvailableDates WHERE available_date='2020-05-27' AND campsite_id=2) BEGIN INSERT INTO AvailableDates( available_date, campsite_id, isAvailable ) VALUES ( '2020-05-27', 2, 1 ) END
IF NOT EXISTS ( SELECT 1 FROM AvailableDates WHERE available_date='2020-05-28' AND campsite_id=2) BEGIN INSERT INTO AvailableDates( available_date, campsite_id, isAvailable ) VALUES ( '2020-05-28', 2, 1 ) END
IF NOT EXISTS ( SELECT 1 FROM AvailableDates WHERE available_date='2020-05-29' AND campsite_id=2) BEGIN INSERT INTO AvailableDates( available_date, campsite_id, isAvailable ) VALUES ( '2020-05-29', 2, 1 ) END
IF NOT EXISTS ( SELECT 1 FROM AvailableDates WHERE available_date='2020-05-30' AND campsite_id=2) BEGIN INSERT INTO AvailableDates( available_date, campsite_id, isAvailable ) VALUES ( '2020-05-30', 2, 1 ) END
IF NOT EXISTS ( SELECT 1 FROM AvailableDates WHERE available_date='2020-05-31' AND campsite_id=2) BEGIN INSERT INTO AvailableDates( available_date, campsite_id, isAvailable ) VALUES ( '2020-05-31', 2, 1 ) END
IF NOT EXISTS ( SELECT 1 FROM AvailableDates WHERE available_date='2020-06-01' AND campsite_id=2) BEGIN INSERT INTO AvailableDates( available_date, campsite_id, isAvailable ) VALUES ( '2020-06-01', 2, 1 ) END
IF NOT EXISTS ( SELECT 1 FROM AvailableDates WHERE available_date='2020-06-02' AND campsite_id=2) BEGIN INSERT INTO AvailableDates( available_date, campsite_id, isAvailable ) VALUES ( '2020-06-02', 2, 1 ) END
IF NOT EXISTS ( SELECT 1 FROM AvailableDates WHERE available_date='2020-06-03' AND campsite_id=2) BEGIN INSERT INTO AvailableDates( available_date, campsite_id, isAvailable ) VALUES ( '2020-06-03', 2, 1 ) END
																																							  
IF NOT EXISTS ( SELECT 1 FROM AvailableDates WHERE available_date='2020-05-25' AND campsite_id=3) BEGIN INSERT INTO AvailableDates( available_date, campsite_id, isAvailable ) VALUES ( '2020-05-25', 3, 1 ) END
IF NOT EXISTS ( SELECT 1 FROM AvailableDates WHERE available_date='2020-05-26' AND campsite_id=3) BEGIN INSERT INTO AvailableDates( available_date, campsite_id, isAvailable ) VALUES ( '2020-05-26', 3, 1 ) END
IF NOT EXISTS ( SELECT 1 FROM AvailableDates WHERE available_date='2020-05-27' AND campsite_id=3) BEGIN INSERT INTO AvailableDates( available_date, campsite_id, isAvailable ) VALUES ( '2020-05-27', 3, 1 ) END
IF NOT EXISTS ( SELECT 1 FROM AvailableDates WHERE available_date='2020-05-28' AND campsite_id=3) BEGIN INSERT INTO AvailableDates( available_date, campsite_id, isAvailable ) VALUES ( '2020-05-28', 3, 1 ) END
IF NOT EXISTS ( SELECT 1 FROM AvailableDates WHERE available_date='2020-05-29' AND campsite_id=3) BEGIN INSERT INTO AvailableDates( available_date, campsite_id, isAvailable ) VALUES ( '2020-05-29', 3, 1 ) END
IF NOT EXISTS ( SELECT 1 FROM AvailableDates WHERE available_date='2020-05-30' AND campsite_id=3) BEGIN INSERT INTO AvailableDates( available_date, campsite_id, isAvailable ) VALUES ( '2020-05-30', 3, 1 ) END
IF NOT EXISTS ( SELECT 1 FROM AvailableDates WHERE available_date='2020-05-31' AND campsite_id=3) BEGIN INSERT INTO AvailableDates( available_date, campsite_id, isAvailable ) VALUES ( '2020-05-31', 3, 1 ) END
IF NOT EXISTS ( SELECT 1 FROM AvailableDates WHERE available_date='2020-06-01' AND campsite_id=3) BEGIN INSERT INTO AvailableDates( available_date, campsite_id, isAvailable ) VALUES ( '2020-06-01', 3, 1 ) END
IF NOT EXISTS ( SELECT 1 FROM AvailableDates WHERE available_date='2020-06-02' AND campsite_id=3) BEGIN INSERT INTO AvailableDates( available_date, campsite_id, isAvailable ) VALUES ( '2020-06-02', 3, 1 ) END
IF NOT EXISTS ( SELECT 1 FROM AvailableDates WHERE available_date='2020-06-03' AND campsite_id=3) BEGIN INSERT INTO AvailableDates( available_date, campsite_id, isAvailable ) VALUES ( '2020-06-03', 3, 1 ) END
																																							   
IF NOT EXISTS ( SELECT 1 FROM AvailableDates WHERE available_date='2020-05-25' AND campsite_id=4) BEGIN INSERT INTO AvailableDates( available_date, campsite_id, isAvailable ) VALUES ( '2020-05-25', 4, 1 ) END
IF NOT EXISTS ( SELECT 1 FROM AvailableDates WHERE available_date='2020-05-26' AND campsite_id=4) BEGIN INSERT INTO AvailableDates( available_date, campsite_id, isAvailable ) VALUES ( '2020-05-26', 4, 1 ) END
IF NOT EXISTS ( SELECT 1 FROM AvailableDates WHERE available_date='2020-05-27' AND campsite_id=4) BEGIN INSERT INTO AvailableDates( available_date, campsite_id, isAvailable ) VALUES ( '2020-05-27', 4, 1 ) END
IF NOT EXISTS ( SELECT 1 FROM AvailableDates WHERE available_date='2020-05-28' AND campsite_id=4) BEGIN INSERT INTO AvailableDates( available_date, campsite_id, isAvailable ) VALUES ( '2020-05-28', 4, 1 ) END
IF NOT EXISTS ( SELECT 1 FROM AvailableDates WHERE available_date='2020-05-29' AND campsite_id=4) BEGIN INSERT INTO AvailableDates( available_date, campsite_id, isAvailable ) VALUES ( '2020-05-29', 4, 1 ) END
IF NOT EXISTS ( SELECT 1 FROM AvailableDates WHERE available_date='2020-05-30' AND campsite_id=4) BEGIN INSERT INTO AvailableDates( available_date, campsite_id, isAvailable ) VALUES ( '2020-05-30', 4, 1 ) END
IF NOT EXISTS ( SELECT 1 FROM AvailableDates WHERE available_date='2020-05-31' AND campsite_id=4) BEGIN INSERT INTO AvailableDates( available_date, campsite_id, isAvailable ) VALUES ( '2020-05-31', 4, 1 ) END
IF NOT EXISTS ( SELECT 1 FROM AvailableDates WHERE available_date='2020-06-01' AND campsite_id=4) BEGIN INSERT INTO AvailableDates( available_date, campsite_id, isAvailable ) VALUES ( '2020-06-01', 4, 1 ) END
IF NOT EXISTS ( SELECT 1 FROM AvailableDates WHERE available_date='2020-06-02' AND campsite_id=4) BEGIN INSERT INTO AvailableDates( available_date, campsite_id, isAvailable ) VALUES ( '2020-06-02', 4, 1 ) END
IF NOT EXISTS ( SELECT 1 FROM AvailableDates WHERE available_date='2020-06-03' AND campsite_id=4) BEGIN INSERT INTO AvailableDates( available_date, campsite_id, isAvailable ) VALUES ( '2020-06-03', 4, 1 ) END
																																							   
IF NOT EXISTS ( SELECT 1 FROM AvailableDates WHERE available_date='2020-05-25' AND campsite_id=5) BEGIN INSERT INTO AvailableDates( available_date, campsite_id, isAvailable ) VALUES ( '2020-05-25', 5, 1 ) END
IF NOT EXISTS ( SELECT 1 FROM AvailableDates WHERE available_date='2020-05-26' AND campsite_id=5) BEGIN INSERT INTO AvailableDates( available_date, campsite_id, isAvailable ) VALUES ( '2020-05-26', 5, 1 ) END
IF NOT EXISTS ( SELECT 1 FROM AvailableDates WHERE available_date='2020-05-27' AND campsite_id=5) BEGIN INSERT INTO AvailableDates( available_date, campsite_id, isAvailable ) VALUES ( '2020-05-27', 5, 1 ) END
IF NOT EXISTS ( SELECT 1 FROM AvailableDates WHERE available_date='2020-05-28' AND campsite_id=5) BEGIN INSERT INTO AvailableDates( available_date, campsite_id, isAvailable ) VALUES ( '2020-05-28', 5, 1 ) END
IF NOT EXISTS ( SELECT 1 FROM AvailableDates WHERE available_date='2020-05-29' AND campsite_id=5) BEGIN INSERT INTO AvailableDates( available_date, campsite_id, isAvailable ) VALUES ( '2020-05-29', 5, 1 ) END
IF NOT EXISTS ( SELECT 1 FROM AvailableDates WHERE available_date='2020-05-30' AND campsite_id=5) BEGIN INSERT INTO AvailableDates( available_date, campsite_id, isAvailable ) VALUES ( '2020-05-30', 5, 1 ) END
IF NOT EXISTS ( SELECT 1 FROM AvailableDates WHERE available_date='2020-05-31' AND campsite_id=5) BEGIN INSERT INTO AvailableDates( available_date, campsite_id, isAvailable ) VALUES ( '2020-05-31', 5, 1 ) END
IF NOT EXISTS ( SELECT 1 FROM AvailableDates WHERE available_date='2020-06-01' AND campsite_id=5) BEGIN INSERT INTO AvailableDates( available_date, campsite_id, isAvailable ) VALUES ( '2020-06-01', 5, 1 ) END
IF NOT EXISTS ( SELECT 1 FROM AvailableDates WHERE available_date='2020-06-02' AND campsite_id=5) BEGIN INSERT INTO AvailableDates( available_date, campsite_id, isAvailable ) VALUES ( '2020-06-02', 5, 1 ) END
IF NOT EXISTS ( SELECT 1 FROM AvailableDates WHERE available_date='2020-06-03' AND campsite_id=5) BEGIN INSERT INTO AvailableDates( available_date, campsite_id, isAvailable ) VALUES ( '2020-06-03', 5, 1 ) END
																																							 
IF NOT EXISTS ( SELECT 1 FROM AvailableDates WHERE available_date='2020-05-25' AND campsite_id=6) BEGIN INSERT INTO AvailableDates( available_date, campsite_id, isAvailable ) VALUES ( '2020-05-25', 6, 1 ) END
IF NOT EXISTS ( SELECT 1 FROM AvailableDates WHERE available_date='2020-05-26' AND campsite_id=6) BEGIN INSERT INTO AvailableDates( available_date, campsite_id, isAvailable ) VALUES ( '2020-05-26', 6, 1 ) END
IF NOT EXISTS ( SELECT 1 FROM AvailableDates WHERE available_date='2020-05-27' AND campsite_id=6) BEGIN INSERT INTO AvailableDates( available_date, campsite_id, isAvailable ) VALUES ( '2020-05-27', 6, 1 ) END
IF NOT EXISTS ( SELECT 1 FROM AvailableDates WHERE available_date='2020-05-28' AND campsite_id=6) BEGIN INSERT INTO AvailableDates( available_date, campsite_id, isAvailable ) VALUES ( '2020-05-28', 6, 1 ) END
IF NOT EXISTS ( SELECT 1 FROM AvailableDates WHERE available_date='2020-05-29' AND campsite_id=6) BEGIN INSERT INTO AvailableDates( available_date, campsite_id, isAvailable ) VALUES ( '2020-05-29', 6, 1 ) END
IF NOT EXISTS ( SELECT 1 FROM AvailableDates WHERE available_date='2020-05-30' AND campsite_id=6) BEGIN INSERT INTO AvailableDates( available_date, campsite_id, isAvailable ) VALUES ( '2020-05-30', 6, 1 ) END
IF NOT EXISTS ( SELECT 1 FROM AvailableDates WHERE available_date='2020-05-31' AND campsite_id=6) BEGIN INSERT INTO AvailableDates( available_date, campsite_id, isAvailable ) VALUES ( '2020-05-31', 6, 1 ) END
IF NOT EXISTS ( SELECT 1 FROM AvailableDates WHERE available_date='2020-06-01' AND campsite_id=6) BEGIN INSERT INTO AvailableDates( available_date, campsite_id, isAvailable ) VALUES ( '2020-06-01', 6, 1 ) END
IF NOT EXISTS ( SELECT 1 FROM AvailableDates WHERE available_date='2020-06-02' AND campsite_id=6) BEGIN INSERT INTO AvailableDates( available_date, campsite_id, isAvailable ) VALUES ( '2020-06-02', 6, 1 ) END
IF NOT EXISTS ( SELECT 1 FROM AvailableDates WHERE available_date='2020-06-03' AND campsite_id=6) BEGIN INSERT INTO AvailableDates( available_date, campsite_id, isAvailable ) VALUES ( '2020-06-03', 6, 1 ) END
																																							  
IF NOT EXISTS ( SELECT 1 FROM AvailableDates WHERE available_date='2020-05-25' AND campsite_id=7) BEGIN INSERT INTO AvailableDates( available_date, campsite_id, isAvailable ) VALUES ( '2020-05-25', 7, 1 ) END
IF NOT EXISTS ( SELECT 1 FROM AvailableDates WHERE available_date='2020-05-26' AND campsite_id=7) BEGIN INSERT INTO AvailableDates( available_date, campsite_id, isAvailable ) VALUES ( '2020-05-26', 7, 1 ) END
IF NOT EXISTS ( SELECT 1 FROM AvailableDates WHERE available_date='2020-05-27' AND campsite_id=7) BEGIN INSERT INTO AvailableDates( available_date, campsite_id, isAvailable ) VALUES ( '2020-05-27', 7, 1 ) END
IF NOT EXISTS ( SELECT 1 FROM AvailableDates WHERE available_date='2020-05-28' AND campsite_id=7) BEGIN INSERT INTO AvailableDates( available_date, campsite_id, isAvailable ) VALUES ( '2020-05-28', 7, 1 ) END
IF NOT EXISTS ( SELECT 1 FROM AvailableDates WHERE available_date='2020-05-29' AND campsite_id=7) BEGIN INSERT INTO AvailableDates( available_date, campsite_id, isAvailable ) VALUES ( '2020-05-29', 7, 1 ) END
IF NOT EXISTS ( SELECT 1 FROM AvailableDates WHERE available_date='2020-05-30' AND campsite_id=7) BEGIN INSERT INTO AvailableDates( available_date, campsite_id, isAvailable ) VALUES ( '2020-05-30', 7, 1 ) END
IF NOT EXISTS ( SELECT 1 FROM AvailableDates WHERE available_date='2020-05-31' AND campsite_id=7) BEGIN INSERT INTO AvailableDates( available_date, campsite_id, isAvailable ) VALUES ( '2020-05-31', 7, 1 ) END
IF NOT EXISTS ( SELECT 1 FROM AvailableDates WHERE available_date='2020-06-01' AND campsite_id=7) BEGIN INSERT INTO AvailableDates( available_date, campsite_id, isAvailable ) VALUES ( '2020-06-01', 7, 1 ) END
IF NOT EXISTS ( SELECT 1 FROM AvailableDates WHERE available_date='2020-06-02' AND campsite_id=7) BEGIN INSERT INTO AvailableDates( available_date, campsite_id, isAvailable ) VALUES ( '2020-06-02', 7, 1 ) END
IF NOT EXISTS ( SELECT 1 FROM AvailableDates WHERE available_date='2020-06-03' AND campsite_id=7) BEGIN INSERT INTO AvailableDates( available_date, campsite_id, isAvailable ) VALUES ( '2020-06-03', 7, 1 ) END
																																							  
IF NOT EXISTS ( SELECT 1 FROM AvailableDates WHERE available_date='2020-05-25' AND campsite_id=8) BEGIN INSERT INTO AvailableDates( available_date, campsite_id, isAvailable ) VALUES ( '2020-05-25', 8, 1 ) END
IF NOT EXISTS ( SELECT 1 FROM AvailableDates WHERE available_date='2020-05-26' AND campsite_id=8) BEGIN INSERT INTO AvailableDates( available_date, campsite_id, isAvailable ) VALUES ( '2020-05-26', 8, 1 ) END
IF NOT EXISTS ( SELECT 1 FROM AvailableDates WHERE available_date='2020-05-27' AND campsite_id=8) BEGIN INSERT INTO AvailableDates( available_date, campsite_id, isAvailable ) VALUES ( '2020-05-27', 8, 1 ) END
IF NOT EXISTS ( SELECT 1 FROM AvailableDates WHERE available_date='2020-05-28' AND campsite_id=8) BEGIN INSERT INTO AvailableDates( available_date, campsite_id, isAvailable ) VALUES ( '2020-05-28', 8, 1 ) END
IF NOT EXISTS ( SELECT 1 FROM AvailableDates WHERE available_date='2020-05-29' AND campsite_id=8) BEGIN INSERT INTO AvailableDates( available_date, campsite_id, isAvailable ) VALUES ( '2020-05-29', 8, 1 ) END
IF NOT EXISTS ( SELECT 1 FROM AvailableDates WHERE available_date='2020-05-30' AND campsite_id=8) BEGIN INSERT INTO AvailableDates( available_date, campsite_id, isAvailable ) VALUES ( '2020-05-30', 8, 1 ) END
IF NOT EXISTS ( SELECT 1 FROM AvailableDates WHERE available_date='2020-05-31' AND campsite_id=8) BEGIN INSERT INTO AvailableDates( available_date, campsite_id, isAvailable ) VALUES ( '2020-05-31', 8, 1 ) END
IF NOT EXISTS ( SELECT 1 FROM AvailableDates WHERE available_date='2020-06-01' AND campsite_id=8) BEGIN INSERT INTO AvailableDates( available_date, campsite_id, isAvailable ) VALUES ( '2020-06-01', 8, 1 ) END
IF NOT EXISTS ( SELECT 1 FROM AvailableDates WHERE available_date='2020-06-02' AND campsite_id=8) BEGIN INSERT INTO AvailableDates( available_date, campsite_id, isAvailable ) VALUES ( '2020-06-02', 8, 1 ) END
IF NOT EXISTS ( SELECT 1 FROM AvailableDates WHERE available_date='2020-06-03' AND campsite_id=8) BEGIN INSERT INTO AvailableDates( available_date, campsite_id, isAvailable ) VALUES ( '2020-06-03', 8, 1 ) END
																																							  
IF NOT EXISTS ( SELECT 1 FROM AvailableDates WHERE available_date='2020-05-25' AND campsite_id=9) BEGIN INSERT INTO AvailableDates( available_date, campsite_id, isAvailable ) VALUES ( '2020-05-25', 9, 1 ) END
IF NOT EXISTS ( SELECT 1 FROM AvailableDates WHERE available_date='2020-05-26' AND campsite_id=9) BEGIN INSERT INTO AvailableDates( available_date, campsite_id, isAvailable ) VALUES ( '2020-05-26', 9, 1 ) END
IF NOT EXISTS ( SELECT 1 FROM AvailableDates WHERE available_date='2020-05-27' AND campsite_id=9) BEGIN INSERT INTO AvailableDates( available_date, campsite_id, isAvailable ) VALUES ( '2020-05-27', 9, 1 ) END
IF NOT EXISTS ( SELECT 1 FROM AvailableDates WHERE available_date='2020-05-28' AND campsite_id=9) BEGIN INSERT INTO AvailableDates( available_date, campsite_id, isAvailable ) VALUES ( '2020-05-28', 9, 1 ) END
IF NOT EXISTS ( SELECT 1 FROM AvailableDates WHERE available_date='2020-05-29' AND campsite_id=9) BEGIN INSERT INTO AvailableDates( available_date, campsite_id, isAvailable ) VALUES ( '2020-05-29', 9, 1 ) END
IF NOT EXISTS ( SELECT 1 FROM AvailableDates WHERE available_date='2020-05-30' AND campsite_id=9) BEGIN INSERT INTO AvailableDates( available_date, campsite_id, isAvailable ) VALUES ( '2020-05-30', 9, 1 ) END
IF NOT EXISTS ( SELECT 1 FROM AvailableDates WHERE available_date='2020-05-31' AND campsite_id=9) BEGIN INSERT INTO AvailableDates( available_date, campsite_id, isAvailable ) VALUES ( '2020-05-31', 9, 1 ) END
IF NOT EXISTS ( SELECT 1 FROM AvailableDates WHERE available_date='2020-06-01' AND campsite_id=9) BEGIN INSERT INTO AvailableDates( available_date, campsite_id, isAvailable ) VALUES ( '2020-06-01', 9, 1 ) END
IF NOT EXISTS ( SELECT 1 FROM AvailableDates WHERE available_date='2020-06-02' AND campsite_id=9) BEGIN INSERT INTO AvailableDates( available_date, campsite_id, isAvailable ) VALUES ( '2020-06-02', 9, 1 ) END
IF NOT EXISTS ( SELECT 1 FROM AvailableDates WHERE available_date='2020-06-03' AND campsite_id=9) BEGIN INSERT INTO AvailableDates( available_date, campsite_id, isAvailable ) VALUES ( '2020-06-03', 9, 1 ) END

IF NOT EXISTS ( SELECT 1 FROM AvailableDates WHERE available_date='2020-05-25' AND campsite_id=10) BEGIN INSERT INTO AvailableDates( available_date, campsite_id, isAvailable ) VALUES ( '2020-05-25', 10, 1 ) END
IF NOT EXISTS ( SELECT 1 FROM AvailableDates WHERE available_date='2020-05-26' AND campsite_id=10) BEGIN INSERT INTO AvailableDates( available_date, campsite_id, isAvailable ) VALUES ( '2020-05-26', 10, 1 ) END
IF NOT EXISTS ( SELECT 1 FROM AvailableDates WHERE available_date='2020-05-27' AND campsite_id=10) BEGIN INSERT INTO AvailableDates( available_date, campsite_id, isAvailable ) VALUES ( '2020-05-27', 10, 1 ) END
IF NOT EXISTS ( SELECT 1 FROM AvailableDates WHERE available_date='2020-05-28' AND campsite_id=10) BEGIN INSERT INTO AvailableDates( available_date, campsite_id, isAvailable ) VALUES ( '2020-05-28', 10, 1 ) END
IF NOT EXISTS ( SELECT 1 FROM AvailableDates WHERE available_date='2020-05-29' AND campsite_id=10) BEGIN INSERT INTO AvailableDates( available_date, campsite_id, isAvailable ) VALUES ( '2020-05-29', 10, 1 ) END
IF NOT EXISTS ( SELECT 1 FROM AvailableDates WHERE available_date='2020-05-30' AND campsite_id=10) BEGIN INSERT INTO AvailableDates( available_date, campsite_id, isAvailable ) VALUES ( '2020-05-30', 10, 1 ) END
IF NOT EXISTS ( SELECT 1 FROM AvailableDates WHERE available_date='2020-05-31' AND campsite_id=10) BEGIN INSERT INTO AvailableDates( available_date, campsite_id, isAvailable ) VALUES ( '2020-05-31', 10, 1 ) END
IF NOT EXISTS ( SELECT 1 FROM AvailableDates WHERE available_date='2020-06-01' AND campsite_id=10) BEGIN INSERT INTO AvailableDates( available_date, campsite_id, isAvailable ) VALUES ( '2020-06-01', 10, 1 ) END
IF NOT EXISTS ( SELECT 1 FROM AvailableDates WHERE available_date='2020-06-02' AND campsite_id=10) BEGIN INSERT INTO AvailableDates( available_date, campsite_id, isAvailable ) VALUES ( '2020-06-02', 10, 1 ) END
IF NOT EXISTS ( SELECT 1 FROM AvailableDates WHERE available_date='2020-06-03' AND campsite_id=10) BEGIN INSERT INTO AvailableDates( available_date, campsite_id, isAvailable ) VALUES ( '2020-06-03', 10, 1 ) END